import { describe, expect, it } from "vitest"
import {
	WarehouseAuthError,
	WarehouseClientError,
	WarehouseConfigError,
	WarehouseInvalidSqlError,
	WarehouseMalformedQueryError,
	WarehouseQueryError,
	WarehouseQuotaExceededError,
	WarehouseSchemaDriftError,
	WarehouseUpstreamError,
} from "@maple/domain/http"
import { cleanErrorMessage, mapWarehouseError, toWarehouseQueryError } from "./errors"
import { WarehouseDriverError } from "./driver-error"

// Promise-land inputs, lifted the way a Promise-based adapter lifts them.
const classify = (pipe: string, error: unknown, authoredBy?: "maple" | "caller") =>
	mapWarehouseError(pipe, WarehouseDriverError.fromUnknown(error), authoredBy)

describe("mapWarehouseError", () => {
	describe("quota", () => {
		it("maps the execution-time code to a quota error", () => {
			const mapped = classify("testPipe", { message: "took too long", code: "159" })
			expect(mapped).toBeInstanceOf(WarehouseQuotaExceededError)
			expect(mapped).toMatchObject({ setting: "max_execution_time", pipeName: "testPipe" })
		})

		it("maps the memory code to a quota error", () => {
			const mapped = classify("testPipe", { message: "out of memory", code: "241" })
			expect(mapped).toBeInstanceOf(WarehouseQuotaExceededError)
			expect(mapped).toMatchObject({ setting: "max_memory_usage" })
		})
	})

	describe("malformed SQL", () => {
		// Captured verbatim from the outage that motivated the SQL catalog sweep:
		// `if(sum(Float64Col) > 0, …, sum(UInt64Col))` on the annual
		// service-overview route, which 502'd every main chart.
		const noCommonType =
			"There is no supertype for types UInt64, Float64  because some of them are integers and some are floating point, but there is no floating point type, that can exactly represent all required integers: While processing if(sum(bEstimatedSpanCount) > 0, sum(bEstimatedSpanCount), sum(bCount)) AS count. (NO_COMMON_TYPE)"

		describe("generated by Maple", () => {
			it("classifies NO_COMMON_TYPE by ClickHouse type", () => {
				const mapped = classify(
					"tracesAllMetricsTimeseries",
					{ message: noCommonType, code: "386", type: "NO_COMMON_TYPE" },
					"maple",
				)
				expect(mapped).toBeInstanceOf(WarehouseMalformedQueryError)
				expect(mapped).toMatchObject({ pipeName: "tracesAllMetricsTimeseries" })
			})

			// Tinybird's /v0/sql returns the text without a structured type field.
			it("classifies NO_COMMON_TYPE from the message alone", () => {
				expect(classify("p", noCommonType, "maple")).toBeInstanceOf(
					WarehouseMalformedQueryError,
				)
			})

			it("classifies an illegal argument type", () => {
				expect(
					classify("p", { message: "boom", type: "ILLEGAL_TYPE_OF_ARGUMENT" }, "maple"),
				).toBeInstanceOf(WarehouseMalformedQueryError)
			})
		})

		// The raw_sql widget and the `run_sql` MCP tool run caller-authored SQL
		// through this same classifier. Claiming their typos as Maple bugs would
		// hide the database's explanation behind "we have been alerted" and page
		// on-call for someone else's mistake.
		describe("written by the caller", () => {
			it("does not blame Maple for a type error in raw SQL", () => {
				const mapped = classify("rawSqlQuery", { message: noCommonType }, "caller")
				expect(mapped).not.toBeInstanceOf(WarehouseMalformedQueryError)
				expect(mapped).toBeInstanceOf(WarehouseInvalidSqlError)
			})

			it("keeps the database's own message so the author can act on it", () => {
				const mapped = classify(
					"rawSqlQuery",
					{
						message: "Illegal type String of argument of function plus",
						type: "ILLEGAL_TYPE_OF_ARGUMENT",
					},
					"caller",
				)
				expect(mapped).toBeInstanceOf(WarehouseInvalidSqlError)
				expect(mapped.message).toContain("Illegal type String of argument")
			})

			// A plain typo used to fall past every authorship-guarded rule into the
			// generic 502 "Database query failed. Contact support", which hid the one
			// thing the author needed: ClickHouse's own explanation.
			it("surfaces a caller's syntax error as invalid SQL rather than a 502", () => {
				const mapped = classify(
					"rawSqlQuery",
					{ message: "Syntax error near FROM", type: "SYNTAX_ERROR" },
					"caller",
				)
				expect(mapped).toBeInstanceOf(WarehouseInvalidSqlError)
				expect(mapped).not.toBeInstanceOf(WarehouseQueryError)
			})

			// The stale `FROM web_events` left in a saved raw_sql widget by the
			// product_events rename: the author's to fix, not a Maple 5xx.
			it("reports a table dropped out from under a saved widget to the author", () => {
				const mapped = classify(
					"rawSqlQuery",
					{
						message: "Unknown table expression identifier 'web_events' in scope SELECT",
						type: "UNKNOWN_TABLE",
					},
					"caller",
				)
				expect(mapped).toBeInstanceOf(WarehouseInvalidSqlError)
				expect(mapped.message).toContain("web_events")
			})

			it("defaults to caller authorship, the conservative reading", () => {
				expect(classify("p", { message: noCommonType })).toBeInstanceOf(
					WarehouseInvalidSqlError,
				)
			})
		})

		// Schema drift is the customer's cluster missing a column, and its remediation
		// is "run schema apply". Only a query MAPLE generated can testify to that: an
		// unknown identifier in caller-authored SQL is a typo in that query.
		//
		// This previously classified as drift for BOTH authors, so `run_sql` agents
		// hitting `Missing columns: t.OrgId` — their own bad alias — told the customer
		// their cluster was out of sync.
		it("classifies an unknown identifier as drift only for Maple-authored SQL", () => {
			expect(
				classify("p", { message: "Missing columns", type: "UNKNOWN_IDENTIFIER" }, "maple"),
			).toBeInstanceOf(WarehouseSchemaDriftError)
		})

		it("classifies an unknown identifier in caller-authored SQL as invalid SQL, not drift", () => {
			const mapped = classify(
				"p",
				{ message: "Missing columns: t.OrgId", type: "UNKNOWN_IDENTIFIER" },
				"caller",
			)
			expect(mapped).toBeInstanceOf(WarehouseInvalidSqlError)
			expect(mapped).not.toBeInstanceOf(WarehouseSchemaDriftError)
		})

		// `mapWarehouseError` defaults to "caller" — the conservative reading — so an
		// unannotated call site must not produce a customer-blaming drift error.
		it("does not claim drift when authorship is unstated", () => {
			expect(
				classify("p", { message: "Missing columns", type: "UNKNOWN_IDENTIFIER" }),
			).not.toBeInstanceOf(WarehouseSchemaDriftError)
		})
	})

	describe("auth", () => {
		it("classifies the auth ClickHouse type", () => {
			expect(classify("p", { message: "nope", type: "AUTHENTICATION_FAILED" })).toBeInstanceOf(
				WarehouseAuthError,
			)
		})

		it("classifies a 401 leaked in the message and keeps the status", () => {
			const mapped = classify("p", "Request failed with status 401")
			expect(mapped).toBeInstanceOf(WarehouseAuthError)
			expect(mapped).toMatchObject({ upstreamStatus: 401 })
		})

		it("classifies Tinybird's invalid-token workspace-not-found message", () => {
			const mapped = classify(
				"p",
				"invalid authentication token. Workspace not found, make sure you use the token host",
			)
			expect(mapped).toBeInstanceOf(WarehouseAuthError)
		})
	})

	describe("upstream", () => {
		it("classifies a 503 and extracts the upstream status", () => {
			const mapped = classify("p", "Request failed with status 503")
			expect(mapped).toBeInstanceOf(WarehouseUpstreamError)
			expect(mapped).toMatchObject({ upstreamStatus: 503 })
		})

		it("classifies a transient ClickHouse type", () => {
			expect(classify("p", { message: "blip", type: "SOCKET_TIMEOUT" })).toBeInstanceOf(
				WarehouseUpstreamError,
			)
		})

		it("classifies a bare timeout message", () => {
			expect(classify("p", "Timeout error")).toBeInstanceOf(WarehouseUpstreamError)
		})
	})

	describe("config", () => {
		// Authorship decides who a missing table indicts. Maple-generated SQL can
		// testify that the warehouse is pointed somewhere wrong; the same complaint
		// about SQL the caller wrote is a typo in their query.
		it("classifies an unknown-database ClickHouse type in Maple-authored SQL", () => {
			expect(
				classify("p", { message: "x", type: "UNKNOWN_DATABASE" }, "maple"),
			).toBeInstanceOf(WarehouseConfigError)
		})

		it("classifies an unknown-database message in Maple-authored SQL", () => {
			expect(classify("p", "Code: 81. unknown database 'foo'", "maple")).toBeInstanceOf(
				WarehouseConfigError,
			)
		})

		it("blames the author, not the warehouse, for a table the caller invented", () => {
			// `maple query "SELECT … FROM spans"` used to come back as a config
			// error, telling someone who mistyped a table name that their warehouse
			// was misconfigured.
			expect(classify("p", { message: "x", type: "UNKNOWN_TABLE" }, "caller")).toBeInstanceOf(
				WarehouseInvalidSqlError,
			)
			expect(
				classify("p", "Code: 60. DB::Exception: Table default.spans does not exist."),
			).toBeInstanceOf(WarehouseInvalidSqlError)
		})

		it("still reads a missing datasource and a bad URL as configuration", () => {
			// Neither names a table the caller chose, so both stay config errors
			// regardless of who wrote the SQL.
			expect(classify("p", "Resource 'product_events' not found")).toBeInstanceOf(
				WarehouseConfigError,
			)
			expect(classify("p", "Invalid URL")).toBeInstanceOf(WarehouseConfigError)
			expect(classify("p", { message: "x", type: "UNKNOWN_SETTING" })).toBeInstanceOf(
				WarehouseConfigError,
			)
		})
	})

	describe("client", () => {
		it("classifies a SyntaxError", () => {
			expect(classify("p", new SyntaxError("Unexpected token < in JSON"))).toBeInstanceOf(
				WarehouseClientError,
			)
		})

		it("classifies a response-parse message", () => {
			expect(classify("p", "Failed to parse ClickHouse response")).toBeInstanceOf(
				WarehouseClientError,
			)
		})
	})

	// Drift is a claim about the customer's cluster, so every case here passes
	// `"maple"` explicitly: it is only diagnosable from SQL we generated.
	describe("schema_drift", () => {
		it("classifies the unknown-identifier ClickHouse type", () => {
			expect(
				classify("p", { message: "x", type: "UNKNOWN_IDENTIFIER" }, "maple"),
			).toBeInstanceOf(WarehouseSchemaDriftError)
		})

		it("classifies an unknown-identifier message", () => {
			expect(
				classify(
					"p",
					"Unknown expression or function identifier 'SampleRate' in scope",
					"maple",
				),
			).toBeInstanceOf(WarehouseSchemaDriftError)
		})
	})

	it("defaults unrecognized errors to the generic query error", () => {
		const mapped = classify("p", "DB::Exception: something we have never seen")
		expect(mapped).toBeInstanceOf(WarehouseQueryError)
		expect(mapped._tag).toBe("@maple/http/errors/WarehouseQueryError")
	})

	it("honors precedence: a transient 503 wins over schema-drift text in the same message", () => {
		expect(classify("p", "Request failed with status 503: No such column 'x'")).toBeInstanceOf(
			WarehouseUpstreamError,
		)
	})

	it("propagates the ClickHouse code and type, coercing a numeric code", () => {
		const mapped = classify("p", { message: "boom", code: 226, type: "SYNTAX_ERROR" })
		expect(mapped.clickhouseCode).toBe("226")
		expect(mapped.clickhouseType).toBe("SYNTAX_ERROR")
	})

	it("threads the original error into cause, underneath the driver error", () => {
		const raw = { message: "boom", type: "SYNTAX_ERROR" }
		const cause = classify("p", raw).cause
		expect(cause).toBeInstanceOf(WarehouseDriverError)
		expect((cause as WarehouseDriverError).cause).toBe(raw)
	})
})

describe("cleanErrorMessage", () => {
	it("retains the authentication diagnostic without the echoed token", () => {
		const message =
			"invalid authentication token. Invalid token b'opaque-secret': Signature verification failed"
		expect(cleanErrorMessage(message)).toBe(
			"invalid authentication token. Invalid token b'[redacted]': Signature verification failed",
		)
		const classified = classify("alertRawQuery", new Error(message))
		expect(classified).toBeInstanceOf(WarehouseAuthError)
		expect(classified.message).not.toContain("opaque-secret")
		expect(String(classified.cause)).not.toContain("opaque-secret")
	})

	it("redacts JWTs from both generic failures and HTML fallbacks", () => {
		const jwt = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0In0.signature"
		const cause = new Error(`Request failed with bearer ${jwt}`)
		const error = toWarehouseQueryError("alertRawQuery", cause)
		expect(error.message).toBe("Request failed with bearer [redacted]")
		expect(String(error.cause)).not.toContain(jwt)
		expect(cleanErrorMessage(`<html>${jwt}</html>`)).not.toContain(jwt)
	})

	it("strips a leaked nginx HTML body", () => {
		const cleaned = cleanErrorMessage(
			"Request failed with status 503: <html><head><title>503 Service Temporarily Unavailable</title></head><body><center><h1>503</h1></center></body></html>",
		)
		expect(cleaned).not.toContain("<")
		expect(cleaned).toBe("Request failed with status 503")
	})

	it("trims a trailing colon", () => {
		expect(cleanErrorMessage("Request failed with status 500:")).toBe("Request failed with status 500")
	})

	it("falls back to the first 200 chars when cleaning empties the message", () => {
		const raw = `<html>${"x".repeat(300)}`
		expect(cleanErrorMessage(raw)).toBe(raw.slice(0, 200))
	})
})

describe("toWarehouseQueryError", () => {
	it("returns a cleaned generic WarehouseQueryError carrying the cause", () => {
		const cause = new Error("DB::Exception: boom  ")
		const mapped = toWarehouseQueryError("testPipe", cause)
		expect(mapped).toBeInstanceOf(WarehouseQueryError)
		expect(mapped.message).toBe("DB::Exception: boom")
		expect(mapped.pipeName).toBe("testPipe")
		expect(mapped.cause).toBe(cause)
	})
})

describe("mapWarehouseError on structured driver errors", () => {
	const driver = (fields: Omit<ConstructorParameters<typeof WarehouseDriverError>[0], "message"> & { message?: string }) =>
		new WarehouseDriverError({ message: "boom", ...fields })

	it("reads the HTTP status from the driver error instead of the message", () => {
		const mapped = mapWarehouseError("p", driver({ reason: "server", status: 503 }))
		expect(mapped).toBeInstanceOf(WarehouseUpstreamError)
		expect(mapped).toMatchObject({ upstreamStatus: 503 })
	})

	it("classifies a 401 with no ClickHouse identity as an auth failure", () => {
		const mapped = mapWarehouseError("p", driver({ reason: "server", status: 401 }))
		expect(mapped).toBeInstanceOf(WarehouseAuthError)
		expect(mapped).toMatchObject({ upstreamStatus: 401 })
	})

	// ClickHouse answers a type mismatch with HTTP 500 on some versions. The code
	// names the failure; the status must not turn it into a retryable outage.
	it("lets a ClickHouse identity outrank a 5xx status", () => {
		const mapped = mapWarehouseError(
			"p",
			driver({ reason: "server", status: 500, code: "386", type: "NO_COMMON_TYPE" }),
			"maple",
		)
		expect(mapped).toBeInstanceOf(WarehouseMalformedQueryError)
	})

	it("treats a transport failure as upstream regardless of its message", () => {
		expect(mapWarehouseError("p", driver({ reason: "transport", message: "socket hang up" }))).toBeInstanceOf(
			WarehouseUpstreamError,
		)
	})

	it("treats an undecodable response as a client failure", () => {
		expect(mapWarehouseError("p", driver({ reason: "protocol", status: 200 }))).toBeInstanceOf(
			WarehouseClientError,
		)
	})

	it("treats a driver refusal as configuration, even with a status attached", () => {
		expect(mapWarehouseError("p", driver({ reason: "config", status: 307 }))).toBeInstanceOf(
			WarehouseConfigError,
		)
	})

	it("keeps the driver error as the cause when nothing was redacted", () => {
		const error = driver({ reason: "server", status: 500 })
		expect(mapWarehouseError("p", error).cause).toBe(error)
	})
})

describe("WarehouseDriverError.fromUnknown", () => {
	it("lifts SDK-style status, code and type fields", () => {
		const lifted = WarehouseDriverError.fromUnknown({
			message: "nope",
			statusCode: 403,
			code: 497,
			type: "ACCESS_DENIED",
		})
		expect(lifted).toMatchObject({ reason: "unknown", status: 403, code: "497", type: "ACCESS_DENIED" })
	})

	it("marks a SyntaxError as a protocol failure", () => {
		expect(WarehouseDriverError.fromUnknown(new SyntaxError("Unexpected token <")).reason).toBe("protocol")
	})

	it("returns an existing driver error unchanged", () => {
		const error = new WarehouseDriverError({ message: "x", reason: "server" })
		expect(WarehouseDriverError.fromUnknown(error)).toBe(error)
	})
})
