/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CliLoginRouteImport } from './routes/cli-login'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LabRouteRouteImport } from './routes/lab/route'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as McpAuthorizeRouteImport } from './routes/mcp-authorize'
import { Route as OrgRequiredRouteImport } from './routes/org-required'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as SelectPlanRouteImport } from './routes/select-plan'
import { Route as ServiceMapRouteImport } from './routes/service-map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AgentSessionsIndexRouteImport } from './routes/agent-sessions/index'
import { Route as AgentSessionsSessionIdRouteImport } from './routes/agent-sessions/$sessionId'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as AlertsRuleIdRouteImport } from './routes/alerts/$ruleId'
import { Route as AlertsCreateRouteImport } from './routes/alerts/create'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AnomaliesIndexRouteImport } from './routes/anomalies/index'
import { Route as AnomaliesIncidentIdRouteImport } from './routes/anomalies/$incidentId'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards/index'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards/$dashboardId'
import { Route as DashboardsTemplatesRouteImport } from './routes/dashboards/templates'
import { Route as ErrorsIndexRouteImport } from './routes/errors/index'
import { Route as InfraIndexRouteImport } from './routes/infra/index'
import { Route as InfraHostNameRouteImport } from './routes/infra/$hostName'
import { Route as InfraDiscoverRouteImport } from './routes/infra/discover'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations/index'
import { Route as InvestigationsIdRouteImport } from './routes/investigations/$id'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as LabAgentSessionRouteImport } from './routes/lab/agent-session'
import { Route as LabAgentSessionsRouteImport } from './routes/lab/agent-sessions'
import { Route as LabChartsRouteImport } from './routes/lab/charts'
import { Route as LabErrorsRouteImport } from './routes/lab/errors'
import { Route as LabFlowRouteImport } from './routes/lab/flow'
import { Route as LabNodesRouteImport } from './routes/lab/nodes'
import { Route as LabOnboardingRouteImport } from './routes/lab/onboarding'
import { Route as LabQueryBuilderRouteImport } from './routes/lab/query-builder'
import { Route as LabServiceMap3dRouteImport } from './routes/lab/service-map-3d'
import { Route as LabTimelineRouteImport } from './routes/lab/timeline'
import { Route as LabWidgetsRouteImport } from './routes/lab/widgets'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as LogsLogIdRouteImport } from './routes/logs/$logId'
import { Route as MetricsIndexRouteImport } from './routes/metrics/index'
import { Route as MetricsMetricNameRouteImport } from './routes/metrics/$metricName'
import { Route as RecommendationsRecommendationKeyRouteImport } from './routes/recommendations/$recommendationKey'
import { Route as ReleasesIndexRouteImport } from './routes/releases/index'
import { Route as ReleasesCommitShaRouteImport } from './routes/releases/$commitSha'
import { Route as ReplaysIndexRouteImport } from './routes/replays/index'
import { Route as ReplaysSessionIdRouteImport } from './routes/replays/$sessionId'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesServiceNameRouteImport } from './routes/services/$serviceName'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'
import { Route as AlertsIncidentsIncidentIdRouteImport } from './routes/alerts/incidents/$incidentId'
import { Route as ErrorsIssuesIndexRouteImport } from './routes/errors/issues/index'
import { Route as ErrorsIssuesIssueIdRouteImport } from './routes/errors/issues/$issueId'
import { Route as InfraCloudflareIndexRouteImport } from './routes/infra/cloudflare/index'
import { Route as InfraCloudflareZoneNameRouteImport } from './routes/infra/cloudflare/$zoneName'
import { Route as InfraContainersIndexRouteImport } from './routes/infra/containers/index'
import { Route as InfraContainersContainerNameRouteImport } from './routes/infra/containers/$containerName'
import { Route as InfraKubernetesIndexRouteImport } from './routes/infra/kubernetes/index'
import { Route as InfraPlanetscaleIndexRouteImport } from './routes/infra/planetscale/index'
import { Route as InfraPlanetscaleDbNameRouteImport } from './routes/infra/planetscale/$dbName'
import { Route as LabBenchAgentTranscriptRouteImport } from './routes/lab/bench/agent-transcript'
import { Route as LabBenchInfraRouteImport } from './routes/lab/bench/infra'
import { Route as LabBenchLogsRouteImport } from './routes/lab/bench/logs'
import { Route as LabBenchOverviewRouteImport } from './routes/lab/bench/overview'
import { Route as LabBenchServiceDetailRouteImport } from './routes/lab/bench/service-detail'
import { Route as LabBenchServiceMapRouteImport } from './routes/lab/bench/service-map'
import { Route as LabBenchTanstackRouteImport } from './routes/lab/bench/tanstack'
import { Route as DashboardsDashboardIdWidgetsWidgetIdRouteImport } from './routes/dashboards/$dashboardId_.widgets.$widgetId'
import { Route as InfraKubernetesNodesIndexRouteImport } from './routes/infra/kubernetes/nodes/index'
import { Route as InfraKubernetesNodesNodeNameRouteImport } from './routes/infra/kubernetes/nodes/$nodeName'
import { Route as InfraKubernetesPodsIndexRouteImport } from './routes/infra/kubernetes/pods/index'
import { Route as InfraKubernetesPodsPodNameRouteImport } from './routes/infra/kubernetes/pods/$podName'
import { Route as InfraKubernetesServicesIndexRouteImport } from './routes/infra/kubernetes/services/index'
import { Route as InfraKubernetesServicesServiceNameRouteImport } from './routes/infra/kubernetes/services/$serviceName'
import { Route as InfraKubernetesWorkloadsIndexRouteImport } from './routes/infra/kubernetes/workloads/index'
import { Route as InfraKubernetesWorkloadsKindWorkloadNameRouteImport } from './routes/infra/kubernetes/workloads/$kind/$workloadName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli-login',
  path: '/cli-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRouteRoute = LabRouteRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: '/mcp-authorize',
  path: '/mcp-authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRequiredRoute = OrgRequiredRouteImport.update({
  id: '/org-required',
  path: '/org-required',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectPlanRoute = SelectPlanRouteImport.update({
  id: '/select-plan',
  path: '/select-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceMapRoute = ServiceMapRouteImport.update({
  id: '/service-map',
  path: '/service-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSessionsIndexRoute = AgentSessionsIndexRouteImport.update({
  id: '/agent-sessions/',
  path: '/agent-sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSessionsSessionIdRoute = AgentSessionsSessionIdRouteImport.update({
  id: '/agent-sessions/$sessionId',
  path: '/agent-sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRuleIdRoute = AlertsRuleIdRouteImport.update({
  id: '/alerts/$ruleId',
  path: '/alerts/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsCreateRoute = AlertsCreateRouteImport.update({
  id: '/alerts/create',
  path: '/alerts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesIndexRoute = AnomaliesIndexRouteImport.update({
  id: '/anomalies/',
  path: '/anomalies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesIncidentIdRoute = AnomaliesIncidentIdRouteImport.update({
  id: '/anomalies/$incidentId',
  path: '/anomalies/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsTemplatesRoute = DashboardsTemplatesRouteImport.update({
  id: '/dashboards/templates',
  path: '/dashboards/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsIndexRoute = ErrorsIndexRouteImport.update({
  id: '/errors/',
  path: '/errors/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraIndexRoute = InfraIndexRouteImport.update({
  id: '/infra/',
  path: '/infra/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraHostNameRoute = InfraHostNameRouteImport.update({
  id: '/infra/$hostName',
  path: '/infra/$hostName',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraDiscoverRoute = InfraDiscoverRouteImport.update({
  id: '/infra/discover',
  path: '/infra/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIdRoute = InvestigationsIdRouteImport.update({
  id: '/investigations/$id',
  path: '/investigations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabAgentSessionRoute = LabAgentSessionRouteImport.update({
  id: '/agent-session',
  path: '/agent-session',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabAgentSessionsRoute = LabAgentSessionsRouteImport.update({
  id: '/agent-sessions',
  path: '/agent-sessions',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabChartsRoute = LabChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabErrorsRoute = LabErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabFlowRoute = LabFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabNodesRoute = LabNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabOnboardingRoute = LabOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabQueryBuilderRoute = LabQueryBuilderRouteImport.update({
  id: '/query-builder',
  path: '/query-builder',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabServiceMap3dRoute = LabServiceMap3dRouteImport.update({
  id: '/service-map-3d',
  path: '/service-map-3d',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabTimelineRoute = LabTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabWidgetsRoute = LabWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => LabRouteRoute,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogIdRoute = LogsLogIdRouteImport.update({
  id: '/logs/$logId',
  path: '/logs/$logId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsMetricNameRoute = MetricsMetricNameRouteImport.update({
  id: '/metrics/$metricName',
  path: '/metrics/$metricName',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRecommendationKeyRoute =
  RecommendationsRecommendationKeyRouteImport.update({
    id: '/recommendations/$recommendationKey',
    path: '/recommendations/$recommendationKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesCommitShaRoute = ReleasesCommitShaRouteImport.update({
  id: '/releases/$commitSha',
  path: '/releases/$commitSha',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysIndexRoute = ReplaysIndexRouteImport.update({
  id: '/replays/',
  path: '/replays/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysSessionIdRoute = ReplaysSessionIdRouteImport.update({
  id: '/replays/$sessionId',
  path: '/replays/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceNameRoute = ServicesServiceNameRouteImport.update({
  id: '/services/$serviceName',
  path: '/services/$serviceName',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIncidentsIncidentIdRoute =
  AlertsIncidentsIncidentIdRouteImport.update({
    id: '/alerts/incidents/$incidentId',
    path: '/alerts/incidents/$incidentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ErrorsIssuesIndexRoute = ErrorsIssuesIndexRouteImport.update({
  id: '/errors/issues/',
  path: '/errors/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsIssuesIssueIdRoute = ErrorsIssuesIssueIdRouteImport.update({
  id: '/errors/issues/$issueId',
  path: '/errors/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraCloudflareIndexRoute = InfraCloudflareIndexRouteImport.update({
  id: '/infra/cloudflare/',
  path: '/infra/cloudflare/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraCloudflareZoneNameRoute = InfraCloudflareZoneNameRouteImport.update({
  id: '/infra/cloudflare/$zoneName',
  path: '/infra/cloudflare/$zoneName',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraContainersIndexRoute = InfraContainersIndexRouteImport.update({
  id: '/infra/containers/',
  path: '/infra/containers/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraContainersContainerNameRoute =
  InfraContainersContainerNameRouteImport.update({
    id: '/infra/containers/$containerName',
    path: '/infra/containers/$containerName',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesIndexRoute = InfraKubernetesIndexRouteImport.update({
  id: '/infra/kubernetes/',
  path: '/infra/kubernetes/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraPlanetscaleIndexRoute = InfraPlanetscaleIndexRouteImport.update({
  id: '/infra/planetscale/',
  path: '/infra/planetscale/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraPlanetscaleDbNameRoute = InfraPlanetscaleDbNameRouteImport.update({
  id: '/infra/planetscale/$dbName',
  path: '/infra/planetscale/$dbName',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBenchAgentTranscriptRoute = LabBenchAgentTranscriptRouteImport.update({
  id: '/bench/agent-transcript',
  path: '/bench/agent-transcript',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabBenchInfraRoute = LabBenchInfraRouteImport.update({
  id: '/bench/infra',
  path: '/bench/infra',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabBenchLogsRoute = LabBenchLogsRouteImport.update({
  id: '/bench/logs',
  path: '/bench/logs',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabBenchOverviewRoute = LabBenchOverviewRouteImport.update({
  id: '/bench/overview',
  path: '/bench/overview',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabBenchServiceDetailRoute = LabBenchServiceDetailRouteImport.update({
  id: '/bench/service-detail',
  path: '/bench/service-detail',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabBenchServiceMapRoute = LabBenchServiceMapRouteImport.update({
  id: '/bench/service-map',
  path: '/bench/service-map',
  getParentRoute: () => LabRouteRoute,
} as any)
const LabBenchTanstackRoute = LabBenchTanstackRouteImport.update({
  id: '/bench/tanstack',
  path: '/bench/tanstack',
  getParentRoute: () => LabRouteRoute,
} as any)
const DashboardsDashboardIdWidgetsWidgetIdRoute =
  DashboardsDashboardIdWidgetsWidgetIdRouteImport.update({
    id: '/dashboards/$dashboardId_/widgets/$widgetId',
    path: '/dashboards/$dashboardId/widgets/$widgetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesNodesIndexRoute =
  InfraKubernetesNodesIndexRouteImport.update({
    id: '/infra/kubernetes/nodes/',
    path: '/infra/kubernetes/nodes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesNodesNodeNameRoute =
  InfraKubernetesNodesNodeNameRouteImport.update({
    id: '/infra/kubernetes/nodes/$nodeName',
    path: '/infra/kubernetes/nodes/$nodeName',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesPodsIndexRoute =
  InfraKubernetesPodsIndexRouteImport.update({
    id: '/infra/kubernetes/pods/',
    path: '/infra/kubernetes/pods/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesPodsPodNameRoute =
  InfraKubernetesPodsPodNameRouteImport.update({
    id: '/infra/kubernetes/pods/$podName',
    path: '/infra/kubernetes/pods/$podName',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesServicesIndexRoute =
  InfraKubernetesServicesIndexRouteImport.update({
    id: '/infra/kubernetes/services/',
    path: '/infra/kubernetes/services/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesServicesServiceNameRoute =
  InfraKubernetesServicesServiceNameRouteImport.update({
    id: '/infra/kubernetes/services/$serviceName',
    path: '/infra/kubernetes/services/$serviceName',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesWorkloadsIndexRoute =
  InfraKubernetesWorkloadsIndexRouteImport.update({
    id: '/infra/kubernetes/workloads/',
    path: '/infra/kubernetes/workloads/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfraKubernetesWorkloadsKindWorkloadNameRoute =
  InfraKubernetesWorkloadsKindWorkloadNameRouteImport.update({
    id: '/infra/kubernetes/workloads/$kind/$workloadName',
    path: '/infra/kubernetes/workloads/$kind/$workloadName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/cli-login': typeof CliLoginRoute
  '/connectors': typeof ConnectorsRoute
  '/developer': typeof DeveloperRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/mcp-authorize': typeof McpAuthorizeRoute
  '/org-required': typeof OrgRequiredRoute
  '/quick-start': typeof QuickStartRoute
  '/select-plan': typeof SelectPlanRoute
  '/service-map': typeof ServiceMapRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/agent-sessions/$sessionId': typeof AgentSessionsSessionIdRoute
  '/alerts/$ruleId': typeof AlertsRuleIdRoute
  '/alerts/create': typeof AlertsCreateRoute
  '/anomalies/$incidentId': typeof AnomaliesIncidentIdRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/dashboards/templates': typeof DashboardsTemplatesRoute
  '/infra/$hostName': typeof InfraHostNameRoute
  '/infra/discover': typeof InfraDiscoverRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/lab/agent-session': typeof LabAgentSessionRoute
  '/lab/agent-sessions': typeof LabAgentSessionsRoute
  '/lab/charts': typeof LabChartsRoute
  '/lab/errors': typeof LabErrorsRoute
  '/lab/flow': typeof LabFlowRoute
  '/lab/nodes': typeof LabNodesRoute
  '/lab/onboarding': typeof LabOnboardingRoute
  '/lab/query-builder': typeof LabQueryBuilderRoute
  '/lab/service-map-3d': typeof LabServiceMap3dRoute
  '/lab/timeline': typeof LabTimelineRoute
  '/lab/widgets': typeof LabWidgetsRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/metrics/$metricName': typeof MetricsMetricNameRoute
  '/recommendations/$recommendationKey': typeof RecommendationsRecommendationKeyRoute
  '/releases/$commitSha': typeof ReleasesCommitShaRoute
  '/replays/$sessionId': typeof ReplaysSessionIdRoute
  '/services/$serviceName': typeof ServicesServiceNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/agent-sessions/': typeof AgentSessionsIndexRoute
  '/alerts/': typeof AlertsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/anomalies/': typeof AnomaliesIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/errors/': typeof ErrorsIndexRoute
  '/infra/': typeof InfraIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/lab/': typeof LabIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/replays/': typeof ReplaysIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/alerts/incidents/$incidentId': typeof AlertsIncidentsIncidentIdRoute
  '/errors/issues/$issueId': typeof ErrorsIssuesIssueIdRoute
  '/infra/cloudflare/$zoneName': typeof InfraCloudflareZoneNameRoute
  '/infra/containers/$containerName': typeof InfraContainersContainerNameRoute
  '/infra/planetscale/$dbName': typeof InfraPlanetscaleDbNameRoute
  '/lab/bench/agent-transcript': typeof LabBenchAgentTranscriptRoute
  '/lab/bench/infra': typeof LabBenchInfraRoute
  '/lab/bench/logs': typeof LabBenchLogsRoute
  '/lab/bench/overview': typeof LabBenchOverviewRoute
  '/lab/bench/service-detail': typeof LabBenchServiceDetailRoute
  '/lab/bench/service-map': typeof LabBenchServiceMapRoute
  '/lab/bench/tanstack': typeof LabBenchTanstackRoute
  '/errors/issues/': typeof ErrorsIssuesIndexRoute
  '/infra/cloudflare/': typeof InfraCloudflareIndexRoute
  '/infra/containers/': typeof InfraContainersIndexRoute
  '/infra/kubernetes/': typeof InfraKubernetesIndexRoute
  '/infra/planetscale/': typeof InfraPlanetscaleIndexRoute
  '/dashboards/$dashboardId/widgets/$widgetId': typeof DashboardsDashboardIdWidgetsWidgetIdRoute
  '/infra/kubernetes/nodes/$nodeName': typeof InfraKubernetesNodesNodeNameRoute
  '/infra/kubernetes/pods/$podName': typeof InfraKubernetesPodsPodNameRoute
  '/infra/kubernetes/services/$serviceName': typeof InfraKubernetesServicesServiceNameRoute
  '/infra/kubernetes/nodes/': typeof InfraKubernetesNodesIndexRoute
  '/infra/kubernetes/pods/': typeof InfraKubernetesPodsIndexRoute
  '/infra/kubernetes/services/': typeof InfraKubernetesServicesIndexRoute
  '/infra/kubernetes/workloads/': typeof InfraKubernetesWorkloadsIndexRoute
  '/infra/kubernetes/workloads/$kind/$workloadName': typeof InfraKubernetesWorkloadsKindWorkloadNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/cli-login': typeof CliLoginRoute
  '/connectors': typeof ConnectorsRoute
  '/developer': typeof DeveloperRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/mcp-authorize': typeof McpAuthorizeRoute
  '/org-required': typeof OrgRequiredRoute
  '/quick-start': typeof QuickStartRoute
  '/select-plan': typeof SelectPlanRoute
  '/service-map': typeof ServiceMapRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/agent-sessions/$sessionId': typeof AgentSessionsSessionIdRoute
  '/alerts/$ruleId': typeof AlertsRuleIdRoute
  '/alerts/create': typeof AlertsCreateRoute
  '/anomalies/$incidentId': typeof AnomaliesIncidentIdRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/dashboards/templates': typeof DashboardsTemplatesRoute
  '/infra/$hostName': typeof InfraHostNameRoute
  '/infra/discover': typeof InfraDiscoverRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/lab/agent-session': typeof LabAgentSessionRoute
  '/lab/agent-sessions': typeof LabAgentSessionsRoute
  '/lab/charts': typeof LabChartsRoute
  '/lab/errors': typeof LabErrorsRoute
  '/lab/flow': typeof LabFlowRoute
  '/lab/nodes': typeof LabNodesRoute
  '/lab/onboarding': typeof LabOnboardingRoute
  '/lab/query-builder': typeof LabQueryBuilderRoute
  '/lab/service-map-3d': typeof LabServiceMap3dRoute
  '/lab/timeline': typeof LabTimelineRoute
  '/lab/widgets': typeof LabWidgetsRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/metrics/$metricName': typeof MetricsMetricNameRoute
  '/recommendations/$recommendationKey': typeof RecommendationsRecommendationKeyRoute
  '/releases/$commitSha': typeof ReleasesCommitShaRoute
  '/replays/$sessionId': typeof ReplaysSessionIdRoute
  '/services/$serviceName': typeof ServicesServiceNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/agent-sessions': typeof AgentSessionsIndexRoute
  '/alerts': typeof AlertsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/anomalies': typeof AnomaliesIndexRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/errors': typeof ErrorsIndexRoute
  '/infra': typeof InfraIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/lab': typeof LabIndexRoute
  '/logs': typeof LogsIndexRoute
  '/metrics': typeof MetricsIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/replays': typeof ReplaysIndexRoute
  '/services': typeof ServicesIndexRoute
  '/traces': typeof TracesIndexRoute
  '/alerts/incidents/$incidentId': typeof AlertsIncidentsIncidentIdRoute
  '/errors/issues/$issueId': typeof ErrorsIssuesIssueIdRoute
  '/infra/cloudflare/$zoneName': typeof InfraCloudflareZoneNameRoute
  '/infra/containers/$containerName': typeof InfraContainersContainerNameRoute
  '/infra/planetscale/$dbName': typeof InfraPlanetscaleDbNameRoute
  '/lab/bench/agent-transcript': typeof LabBenchAgentTranscriptRoute
  '/lab/bench/infra': typeof LabBenchInfraRoute
  '/lab/bench/logs': typeof LabBenchLogsRoute
  '/lab/bench/overview': typeof LabBenchOverviewRoute
  '/lab/bench/service-detail': typeof LabBenchServiceDetailRoute
  '/lab/bench/service-map': typeof LabBenchServiceMapRoute
  '/lab/bench/tanstack': typeof LabBenchTanstackRoute
  '/errors/issues': typeof ErrorsIssuesIndexRoute
  '/infra/cloudflare': typeof InfraCloudflareIndexRoute
  '/infra/containers': typeof InfraContainersIndexRoute
  '/infra/kubernetes': typeof InfraKubernetesIndexRoute
  '/infra/planetscale': typeof InfraPlanetscaleIndexRoute
  '/dashboards/$dashboardId/widgets/$widgetId': typeof DashboardsDashboardIdWidgetsWidgetIdRoute
  '/infra/kubernetes/nodes/$nodeName': typeof InfraKubernetesNodesNodeNameRoute
  '/infra/kubernetes/pods/$podName': typeof InfraKubernetesPodsPodNameRoute
  '/infra/kubernetes/services/$serviceName': typeof InfraKubernetesServicesServiceNameRoute
  '/infra/kubernetes/nodes': typeof InfraKubernetesNodesIndexRoute
  '/infra/kubernetes/pods': typeof InfraKubernetesPodsIndexRoute
  '/infra/kubernetes/services': typeof InfraKubernetesServicesIndexRoute
  '/infra/kubernetes/workloads': typeof InfraKubernetesWorkloadsIndexRoute
  '/infra/kubernetes/workloads/$kind/$workloadName': typeof InfraKubernetesWorkloadsKindWorkloadNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/chat': typeof ChatRoute
  '/cli-login': typeof CliLoginRoute
  '/connectors': typeof ConnectorsRoute
  '/developer': typeof DeveloperRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/mcp-authorize': typeof McpAuthorizeRoute
  '/org-required': typeof OrgRequiredRoute
  '/quick-start': typeof QuickStartRoute
  '/select-plan': typeof SelectPlanRoute
  '/service-map': typeof ServiceMapRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/agent-sessions/$sessionId': typeof AgentSessionsSessionIdRoute
  '/alerts/$ruleId': typeof AlertsRuleIdRoute
  '/alerts/create': typeof AlertsCreateRoute
  '/anomalies/$incidentId': typeof AnomaliesIncidentIdRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/dashboards/templates': typeof DashboardsTemplatesRoute
  '/infra/$hostName': typeof InfraHostNameRoute
  '/infra/discover': typeof InfraDiscoverRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/lab/agent-session': typeof LabAgentSessionRoute
  '/lab/agent-sessions': typeof LabAgentSessionsRoute
  '/lab/charts': typeof LabChartsRoute
  '/lab/errors': typeof LabErrorsRoute
  '/lab/flow': typeof LabFlowRoute
  '/lab/nodes': typeof LabNodesRoute
  '/lab/onboarding': typeof LabOnboardingRoute
  '/lab/query-builder': typeof LabQueryBuilderRoute
  '/lab/service-map-3d': typeof LabServiceMap3dRoute
  '/lab/timeline': typeof LabTimelineRoute
  '/lab/widgets': typeof LabWidgetsRoute
  '/logs/$logId': typeof LogsLogIdRoute
  '/metrics/$metricName': typeof MetricsMetricNameRoute
  '/recommendations/$recommendationKey': typeof RecommendationsRecommendationKeyRoute
  '/releases/$commitSha': typeof ReleasesCommitShaRoute
  '/replays/$sessionId': typeof ReplaysSessionIdRoute
  '/services/$serviceName': typeof ServicesServiceNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/agent-sessions/': typeof AgentSessionsIndexRoute
  '/alerts/': typeof AlertsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/anomalies/': typeof AnomaliesIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/errors/': typeof ErrorsIndexRoute
  '/infra/': typeof InfraIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/lab/': typeof LabIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/replays/': typeof ReplaysIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/alerts/incidents/$incidentId': typeof AlertsIncidentsIncidentIdRoute
  '/errors/issues/$issueId': typeof ErrorsIssuesIssueIdRoute
  '/infra/cloudflare/$zoneName': typeof InfraCloudflareZoneNameRoute
  '/infra/containers/$containerName': typeof InfraContainersContainerNameRoute
  '/infra/planetscale/$dbName': typeof InfraPlanetscaleDbNameRoute
  '/lab/bench/agent-transcript': typeof LabBenchAgentTranscriptRoute
  '/lab/bench/infra': typeof LabBenchInfraRoute
  '/lab/bench/logs': typeof LabBenchLogsRoute
  '/lab/bench/overview': typeof LabBenchOverviewRoute
  '/lab/bench/service-detail': typeof LabBenchServiceDetailRoute
  '/lab/bench/service-map': typeof LabBenchServiceMapRoute
  '/lab/bench/tanstack': typeof LabBenchTanstackRoute
  '/errors/issues/': typeof ErrorsIssuesIndexRoute
  '/infra/cloudflare/': typeof InfraCloudflareIndexRoute
  '/infra/containers/': typeof InfraContainersIndexRoute
  '/infra/kubernetes/': typeof InfraKubernetesIndexRoute
  '/infra/planetscale/': typeof InfraPlanetscaleIndexRoute
  '/dashboards/$dashboardId_/widgets/$widgetId': typeof DashboardsDashboardIdWidgetsWidgetIdRoute
  '/infra/kubernetes/nodes/$nodeName': typeof InfraKubernetesNodesNodeNameRoute
  '/infra/kubernetes/pods/$podName': typeof InfraKubernetesPodsPodNameRoute
  '/infra/kubernetes/services/$serviceName': typeof InfraKubernetesServicesServiceNameRoute
  '/infra/kubernetes/nodes/': typeof InfraKubernetesNodesIndexRoute
  '/infra/kubernetes/pods/': typeof InfraKubernetesPodsIndexRoute
  '/infra/kubernetes/services/': typeof InfraKubernetesServicesIndexRoute
  '/infra/kubernetes/workloads/': typeof InfraKubernetesWorkloadsIndexRoute
  '/infra/kubernetes/workloads/$kind/$workloadName': typeof InfraKubernetesWorkloadsKindWorkloadNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/account'
    | '/chat'
    | '/cli-login'
    | '/connectors'
    | '/developer'
    | '/integrations'
    | '/mcp'
    | '/mcp-authorize'
    | '/org-required'
    | '/quick-start'
    | '/select-plan'
    | '/service-map'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/agent-sessions/$sessionId'
    | '/alerts/$ruleId'
    | '/alerts/create'
    | '/anomalies/$incidentId'
    | '/dashboards/$dashboardId'
    | '/dashboards/templates'
    | '/infra/$hostName'
    | '/infra/discover'
    | '/investigations/$id'
    | '/lab/agent-session'
    | '/lab/agent-sessions'
    | '/lab/charts'
    | '/lab/errors'
    | '/lab/flow'
    | '/lab/nodes'
    | '/lab/onboarding'
    | '/lab/query-builder'
    | '/lab/service-map-3d'
    | '/lab/timeline'
    | '/lab/widgets'
    | '/logs/$logId'
    | '/metrics/$metricName'
    | '/recommendations/$recommendationKey'
    | '/releases/$commitSha'
    | '/replays/$sessionId'
    | '/services/$serviceName'
    | '/share/$token'
    | '/traces/$traceId'
    | '/agent-sessions/'
    | '/alerts/'
    | '/analytics/'
    | '/anomalies/'
    | '/dashboards/'
    | '/errors/'
    | '/infra/'
    | '/investigations/'
    | '/lab/'
    | '/logs/'
    | '/metrics/'
    | '/releases/'
    | '/replays/'
    | '/services/'
    | '/traces/'
    | '/alerts/incidents/$incidentId'
    | '/errors/issues/$issueId'
    | '/infra/cloudflare/$zoneName'
    | '/infra/containers/$containerName'
    | '/infra/planetscale/$dbName'
    | '/lab/bench/agent-transcript'
    | '/lab/bench/infra'
    | '/lab/bench/logs'
    | '/lab/bench/overview'
    | '/lab/bench/service-detail'
    | '/lab/bench/service-map'
    | '/lab/bench/tanstack'
    | '/errors/issues/'
    | '/infra/cloudflare/'
    | '/infra/containers/'
    | '/infra/kubernetes/'
    | '/infra/planetscale/'
    | '/dashboards/$dashboardId/widgets/$widgetId'
    | '/infra/kubernetes/nodes/$nodeName'
    | '/infra/kubernetes/pods/$podName'
    | '/infra/kubernetes/services/$serviceName'
    | '/infra/kubernetes/nodes/'
    | '/infra/kubernetes/pods/'
    | '/infra/kubernetes/services/'
    | '/infra/kubernetes/workloads/'
    | '/infra/kubernetes/workloads/$kind/$workloadName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/chat'
    | '/cli-login'
    | '/connectors'
    | '/developer'
    | '/integrations'
    | '/mcp'
    | '/mcp-authorize'
    | '/org-required'
    | '/quick-start'
    | '/select-plan'
    | '/service-map'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/agent-sessions/$sessionId'
    | '/alerts/$ruleId'
    | '/alerts/create'
    | '/anomalies/$incidentId'
    | '/dashboards/$dashboardId'
    | '/dashboards/templates'
    | '/infra/$hostName'
    | '/infra/discover'
    | '/investigations/$id'
    | '/lab/agent-session'
    | '/lab/agent-sessions'
    | '/lab/charts'
    | '/lab/errors'
    | '/lab/flow'
    | '/lab/nodes'
    | '/lab/onboarding'
    | '/lab/query-builder'
    | '/lab/service-map-3d'
    | '/lab/timeline'
    | '/lab/widgets'
    | '/logs/$logId'
    | '/metrics/$metricName'
    | '/recommendations/$recommendationKey'
    | '/releases/$commitSha'
    | '/replays/$sessionId'
    | '/services/$serviceName'
    | '/share/$token'
    | '/traces/$traceId'
    | '/agent-sessions'
    | '/alerts'
    | '/analytics'
    | '/anomalies'
    | '/dashboards'
    | '/errors'
    | '/infra'
    | '/investigations'
    | '/lab'
    | '/logs'
    | '/metrics'
    | '/releases'
    | '/replays'
    | '/services'
    | '/traces'
    | '/alerts/incidents/$incidentId'
    | '/errors/issues/$issueId'
    | '/infra/cloudflare/$zoneName'
    | '/infra/containers/$containerName'
    | '/infra/planetscale/$dbName'
    | '/lab/bench/agent-transcript'
    | '/lab/bench/infra'
    | '/lab/bench/logs'
    | '/lab/bench/overview'
    | '/lab/bench/service-detail'
    | '/lab/bench/service-map'
    | '/lab/bench/tanstack'
    | '/errors/issues'
    | '/infra/cloudflare'
    | '/infra/containers'
    | '/infra/kubernetes'
    | '/infra/planetscale'
    | '/dashboards/$dashboardId/widgets/$widgetId'
    | '/infra/kubernetes/nodes/$nodeName'
    | '/infra/kubernetes/pods/$podName'
    | '/infra/kubernetes/services/$serviceName'
    | '/infra/kubernetes/nodes'
    | '/infra/kubernetes/pods'
    | '/infra/kubernetes/services'
    | '/infra/kubernetes/workloads'
    | '/infra/kubernetes/workloads/$kind/$workloadName'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/account'
    | '/chat'
    | '/cli-login'
    | '/connectors'
    | '/developer'
    | '/integrations'
    | '/mcp'
    | '/mcp-authorize'
    | '/org-required'
    | '/quick-start'
    | '/select-plan'
    | '/service-map'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/agent-sessions/$sessionId'
    | '/alerts/$ruleId'
    | '/alerts/create'
    | '/anomalies/$incidentId'
    | '/dashboards/$dashboardId'
    | '/dashboards/templates'
    | '/infra/$hostName'
    | '/infra/discover'
    | '/investigations/$id'
    | '/lab/agent-session'
    | '/lab/agent-sessions'
    | '/lab/charts'
    | '/lab/errors'
    | '/lab/flow'
    | '/lab/nodes'
    | '/lab/onboarding'
    | '/lab/query-builder'
    | '/lab/service-map-3d'
    | '/lab/timeline'
    | '/lab/widgets'
    | '/logs/$logId'
    | '/metrics/$metricName'
    | '/recommendations/$recommendationKey'
    | '/releases/$commitSha'
    | '/replays/$sessionId'
    | '/services/$serviceName'
    | '/share/$token'
    | '/traces/$traceId'
    | '/agent-sessions/'
    | '/alerts/'
    | '/analytics/'
    | '/anomalies/'
    | '/dashboards/'
    | '/errors/'
    | '/infra/'
    | '/investigations/'
    | '/lab/'
    | '/logs/'
    | '/metrics/'
    | '/releases/'
    | '/replays/'
    | '/services/'
    | '/traces/'
    | '/alerts/incidents/$incidentId'
    | '/errors/issues/$issueId'
    | '/infra/cloudflare/$zoneName'
    | '/infra/containers/$containerName'
    | '/infra/planetscale/$dbName'
    | '/lab/bench/agent-transcript'
    | '/lab/bench/infra'
    | '/lab/bench/logs'
    | '/lab/bench/overview'
    | '/lab/bench/service-detail'
    | '/lab/bench/service-map'
    | '/lab/bench/tanstack'
    | '/errors/issues/'
    | '/infra/cloudflare/'
    | '/infra/containers/'
    | '/infra/kubernetes/'
    | '/infra/planetscale/'
    | '/dashboards/$dashboardId_/widgets/$widgetId'
    | '/infra/kubernetes/nodes/$nodeName'
    | '/infra/kubernetes/pods/$podName'
    | '/infra/kubernetes/services/$serviceName'
    | '/infra/kubernetes/nodes/'
    | '/infra/kubernetes/pods/'
    | '/infra/kubernetes/services/'
    | '/infra/kubernetes/workloads/'
    | '/infra/kubernetes/workloads/$kind/$workloadName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRouteRoute: typeof LabRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  ChatRoute: typeof ChatRoute
  CliLoginRoute: typeof CliLoginRoute
  ConnectorsRoute: typeof ConnectorsRoute
  DeveloperRoute: typeof DeveloperRoute
  IntegrationsRoute: typeof IntegrationsRoute
  McpRoute: typeof McpRoute
  McpAuthorizeRoute: typeof McpAuthorizeRoute
  OrgRequiredRoute: typeof OrgRequiredRoute
  QuickStartRoute: typeof QuickStartRoute
  SelectPlanRoute: typeof SelectPlanRoute
  ServiceMapRoute: typeof ServiceMapRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AgentSessionsSessionIdRoute: typeof AgentSessionsSessionIdRoute
  AlertsRuleIdRoute: typeof AlertsRuleIdRoute
  AlertsCreateRoute: typeof AlertsCreateRoute
  AnomaliesIncidentIdRoute: typeof AnomaliesIncidentIdRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRoute
  DashboardsTemplatesRoute: typeof DashboardsTemplatesRoute
  InfraHostNameRoute: typeof InfraHostNameRoute
  InfraDiscoverRoute: typeof InfraDiscoverRoute
  InvestigationsIdRoute: typeof InvestigationsIdRoute
  LogsLogIdRoute: typeof LogsLogIdRoute
  MetricsMetricNameRoute: typeof MetricsMetricNameRoute
  RecommendationsRecommendationKeyRoute: typeof RecommendationsRecommendationKeyRoute
  ReleasesCommitShaRoute: typeof ReleasesCommitShaRoute
  ReplaysSessionIdRoute: typeof ReplaysSessionIdRoute
  ServicesServiceNameRoute: typeof ServicesServiceNameRoute
  ShareTokenRoute: typeof ShareTokenRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  AgentSessionsIndexRoute: typeof AgentSessionsIndexRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  AnomaliesIndexRoute: typeof AnomaliesIndexRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  ErrorsIndexRoute: typeof ErrorsIndexRoute
  InfraIndexRoute: typeof InfraIndexRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
  ReplaysIndexRoute: typeof ReplaysIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
  AlertsIncidentsIncidentIdRoute: typeof AlertsIncidentsIncidentIdRoute
  ErrorsIssuesIssueIdRoute: typeof ErrorsIssuesIssueIdRoute
  InfraCloudflareZoneNameRoute: typeof InfraCloudflareZoneNameRoute
  InfraContainersContainerNameRoute: typeof InfraContainersContainerNameRoute
  InfraPlanetscaleDbNameRoute: typeof InfraPlanetscaleDbNameRoute
  ErrorsIssuesIndexRoute: typeof ErrorsIssuesIndexRoute
  InfraCloudflareIndexRoute: typeof InfraCloudflareIndexRoute
  InfraContainersIndexRoute: typeof InfraContainersIndexRoute
  InfraKubernetesIndexRoute: typeof InfraKubernetesIndexRoute
  InfraPlanetscaleIndexRoute: typeof InfraPlanetscaleIndexRoute
  DashboardsDashboardIdWidgetsWidgetIdRoute: typeof DashboardsDashboardIdWidgetsWidgetIdRoute
  InfraKubernetesNodesNodeNameRoute: typeof InfraKubernetesNodesNodeNameRoute
  InfraKubernetesPodsPodNameRoute: typeof InfraKubernetesPodsPodNameRoute
  InfraKubernetesServicesServiceNameRoute: typeof InfraKubernetesServicesServiceNameRoute
  InfraKubernetesNodesIndexRoute: typeof InfraKubernetesNodesIndexRoute
  InfraKubernetesPodsIndexRoute: typeof InfraKubernetesPodsIndexRoute
  InfraKubernetesServicesIndexRoute: typeof InfraKubernetesServicesIndexRoute
  InfraKubernetesWorkloadsIndexRoute: typeof InfraKubernetesWorkloadsIndexRoute
  InfraKubernetesWorkloadsKindWorkloadNameRoute: typeof InfraKubernetesWorkloadsKindWorkloadNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-login': {
      id: '/cli-login'
      path: '/cli-login'
      fullPath: '/cli-login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-authorize': {
      id: '/mcp-authorize'
      path: '/mcp-authorize'
      fullPath: '/mcp-authorize'
      preLoaderRoute: typeof McpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-required': {
      id: '/org-required'
      path: '/org-required'
      fullPath: '/org-required'
      preLoaderRoute: typeof OrgRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-plan': {
      id: '/select-plan'
      path: '/select-plan'
      fullPath: '/select-plan'
      preLoaderRoute: typeof SelectPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-map': {
      id: '/service-map'
      path: '/service-map'
      fullPath: '/service-map'
      preLoaderRoute: typeof ServiceMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-sessions/': {
      id: '/agent-sessions/'
      path: '/agent-sessions'
      fullPath: '/agent-sessions/'
      preLoaderRoute: typeof AgentSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-sessions/$sessionId': {
      id: '/agent-sessions/$sessionId'
      path: '/agent-sessions/$sessionId'
      fullPath: '/agent-sessions/$sessionId'
      preLoaderRoute: typeof AgentSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$ruleId': {
      id: '/alerts/$ruleId'
      path: '/alerts/$ruleId'
      fullPath: '/alerts/$ruleId'
      preLoaderRoute: typeof AlertsRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/create': {
      id: '/alerts/create'
      path: '/alerts/create'
      fullPath: '/alerts/create'
      preLoaderRoute: typeof AlertsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies/': {
      id: '/anomalies/'
      path: '/anomalies'
      fullPath: '/anomalies/'
      preLoaderRoute: typeof AnomaliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies/$incidentId': {
      id: '/anomalies/$incidentId'
      path: '/anomalies/$incidentId'
      fullPath: '/anomalies/$incidentId'
      preLoaderRoute: typeof AnomaliesIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/templates': {
      id: '/dashboards/templates'
      path: '/dashboards/templates'
      fullPath: '/dashboards/templates'
      preLoaderRoute: typeof DashboardsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/': {
      id: '/errors/'
      path: '/errors'
      fullPath: '/errors/'
      preLoaderRoute: typeof ErrorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/': {
      id: '/infra/'
      path: '/infra'
      fullPath: '/infra/'
      preLoaderRoute: typeof InfraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/$hostName': {
      id: '/infra/$hostName'
      path: '/infra/$hostName'
      fullPath: '/infra/$hostName'
      preLoaderRoute: typeof InfraHostNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/discover': {
      id: '/infra/discover'
      path: '/infra/discover'
      fullPath: '/infra/discover'
      preLoaderRoute: typeof InfraDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$id': {
      id: '/investigations/$id'
      path: '/investigations/$id'
      fullPath: '/investigations/$id'
      preLoaderRoute: typeof InvestigationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/agent-session': {
      id: '/lab/agent-session'
      path: '/agent-session'
      fullPath: '/lab/agent-session'
      preLoaderRoute: typeof LabAgentSessionRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/agent-sessions': {
      id: '/lab/agent-sessions'
      path: '/agent-sessions'
      fullPath: '/lab/agent-sessions'
      preLoaderRoute: typeof LabAgentSessionsRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/charts': {
      id: '/lab/charts'
      path: '/charts'
      fullPath: '/lab/charts'
      preLoaderRoute: typeof LabChartsRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/errors': {
      id: '/lab/errors'
      path: '/errors'
      fullPath: '/lab/errors'
      preLoaderRoute: typeof LabErrorsRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/flow': {
      id: '/lab/flow'
      path: '/flow'
      fullPath: '/lab/flow'
      preLoaderRoute: typeof LabFlowRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/nodes': {
      id: '/lab/nodes'
      path: '/nodes'
      fullPath: '/lab/nodes'
      preLoaderRoute: typeof LabNodesRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/onboarding': {
      id: '/lab/onboarding'
      path: '/onboarding'
      fullPath: '/lab/onboarding'
      preLoaderRoute: typeof LabOnboardingRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/query-builder': {
      id: '/lab/query-builder'
      path: '/query-builder'
      fullPath: '/lab/query-builder'
      preLoaderRoute: typeof LabQueryBuilderRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/service-map-3d': {
      id: '/lab/service-map-3d'
      path: '/service-map-3d'
      fullPath: '/lab/service-map-3d'
      preLoaderRoute: typeof LabServiceMap3dRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/timeline': {
      id: '/lab/timeline'
      path: '/timeline'
      fullPath: '/lab/timeline'
      preLoaderRoute: typeof LabTimelineRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/widgets': {
      id: '/lab/widgets'
      path: '/widgets'
      fullPath: '/lab/widgets'
      preLoaderRoute: typeof LabWidgetsRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$logId': {
      id: '/logs/$logId'
      path: '/logs/$logId'
      fullPath: '/logs/$logId'
      preLoaderRoute: typeof LogsLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/metrics'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/$metricName': {
      id: '/metrics/$metricName'
      path: '/metrics/$metricName'
      fullPath: '/metrics/$metricName'
      preLoaderRoute: typeof MetricsMetricNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/$recommendationKey': {
      id: '/recommendations/$recommendationKey'
      path: '/recommendations/$recommendationKey'
      fullPath: '/recommendations/$recommendationKey'
      preLoaderRoute: typeof RecommendationsRecommendationKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/': {
      id: '/releases/'
      path: '/releases'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$commitSha': {
      id: '/releases/$commitSha'
      path: '/releases/$commitSha'
      fullPath: '/releases/$commitSha'
      preLoaderRoute: typeof ReleasesCommitShaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays/': {
      id: '/replays/'
      path: '/replays'
      fullPath: '/replays/'
      preLoaderRoute: typeof ReplaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays/$sessionId': {
      id: '/replays/$sessionId'
      path: '/replays/$sessionId'
      fullPath: '/replays/$sessionId'
      preLoaderRoute: typeof ReplaysSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceName': {
      id: '/services/$serviceName'
      path: '/services/$serviceName'
      fullPath: '/services/$serviceName'
      preLoaderRoute: typeof ServicesServiceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/incidents/$incidentId': {
      id: '/alerts/incidents/$incidentId'
      path: '/alerts/incidents/$incidentId'
      fullPath: '/alerts/incidents/$incidentId'
      preLoaderRoute: typeof AlertsIncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/issues/': {
      id: '/errors/issues/'
      path: '/errors/issues'
      fullPath: '/errors/issues/'
      preLoaderRoute: typeof ErrorsIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/issues/$issueId': {
      id: '/errors/issues/$issueId'
      path: '/errors/issues/$issueId'
      fullPath: '/errors/issues/$issueId'
      preLoaderRoute: typeof ErrorsIssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/cloudflare/': {
      id: '/infra/cloudflare/'
      path: '/infra/cloudflare'
      fullPath: '/infra/cloudflare/'
      preLoaderRoute: typeof InfraCloudflareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/cloudflare/$zoneName': {
      id: '/infra/cloudflare/$zoneName'
      path: '/infra/cloudflare/$zoneName'
      fullPath: '/infra/cloudflare/$zoneName'
      preLoaderRoute: typeof InfraCloudflareZoneNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/containers/': {
      id: '/infra/containers/'
      path: '/infra/containers'
      fullPath: '/infra/containers/'
      preLoaderRoute: typeof InfraContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/containers/$containerName': {
      id: '/infra/containers/$containerName'
      path: '/infra/containers/$containerName'
      fullPath: '/infra/containers/$containerName'
      preLoaderRoute: typeof InfraContainersContainerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/': {
      id: '/infra/kubernetes/'
      path: '/infra/kubernetes'
      fullPath: '/infra/kubernetes/'
      preLoaderRoute: typeof InfraKubernetesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/planetscale/': {
      id: '/infra/planetscale/'
      path: '/infra/planetscale'
      fullPath: '/infra/planetscale/'
      preLoaderRoute: typeof InfraPlanetscaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/planetscale/$dbName': {
      id: '/infra/planetscale/$dbName'
      path: '/infra/planetscale/$dbName'
      fullPath: '/infra/planetscale/$dbName'
      preLoaderRoute: typeof InfraPlanetscaleDbNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/bench/agent-transcript': {
      id: '/lab/bench/agent-transcript'
      path: '/bench/agent-transcript'
      fullPath: '/lab/bench/agent-transcript'
      preLoaderRoute: typeof LabBenchAgentTranscriptRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/bench/infra': {
      id: '/lab/bench/infra'
      path: '/bench/infra'
      fullPath: '/lab/bench/infra'
      preLoaderRoute: typeof LabBenchInfraRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/bench/logs': {
      id: '/lab/bench/logs'
      path: '/bench/logs'
      fullPath: '/lab/bench/logs'
      preLoaderRoute: typeof LabBenchLogsRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/bench/overview': {
      id: '/lab/bench/overview'
      path: '/bench/overview'
      fullPath: '/lab/bench/overview'
      preLoaderRoute: typeof LabBenchOverviewRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/bench/service-detail': {
      id: '/lab/bench/service-detail'
      path: '/bench/service-detail'
      fullPath: '/lab/bench/service-detail'
      preLoaderRoute: typeof LabBenchServiceDetailRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/bench/service-map': {
      id: '/lab/bench/service-map'
      path: '/bench/service-map'
      fullPath: '/lab/bench/service-map'
      preLoaderRoute: typeof LabBenchServiceMapRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/lab/bench/tanstack': {
      id: '/lab/bench/tanstack'
      path: '/bench/tanstack'
      fullPath: '/lab/bench/tanstack'
      preLoaderRoute: typeof LabBenchTanstackRouteImport
      parentRoute: typeof LabRouteRoute
    }
    '/dashboards/$dashboardId_/widgets/$widgetId': {
      id: '/dashboards/$dashboardId_/widgets/$widgetId'
      path: '/dashboards/$dashboardId/widgets/$widgetId'
      fullPath: '/dashboards/$dashboardId/widgets/$widgetId'
      preLoaderRoute: typeof DashboardsDashboardIdWidgetsWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/nodes/': {
      id: '/infra/kubernetes/nodes/'
      path: '/infra/kubernetes/nodes'
      fullPath: '/infra/kubernetes/nodes/'
      preLoaderRoute: typeof InfraKubernetesNodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/nodes/$nodeName': {
      id: '/infra/kubernetes/nodes/$nodeName'
      path: '/infra/kubernetes/nodes/$nodeName'
      fullPath: '/infra/kubernetes/nodes/$nodeName'
      preLoaderRoute: typeof InfraKubernetesNodesNodeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/pods/': {
      id: '/infra/kubernetes/pods/'
      path: '/infra/kubernetes/pods'
      fullPath: '/infra/kubernetes/pods/'
      preLoaderRoute: typeof InfraKubernetesPodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/pods/$podName': {
      id: '/infra/kubernetes/pods/$podName'
      path: '/infra/kubernetes/pods/$podName'
      fullPath: '/infra/kubernetes/pods/$podName'
      preLoaderRoute: typeof InfraKubernetesPodsPodNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/services/': {
      id: '/infra/kubernetes/services/'
      path: '/infra/kubernetes/services'
      fullPath: '/infra/kubernetes/services/'
      preLoaderRoute: typeof InfraKubernetesServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/services/$serviceName': {
      id: '/infra/kubernetes/services/$serviceName'
      path: '/infra/kubernetes/services/$serviceName'
      fullPath: '/infra/kubernetes/services/$serviceName'
      preLoaderRoute: typeof InfraKubernetesServicesServiceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/workloads/': {
      id: '/infra/kubernetes/workloads/'
      path: '/infra/kubernetes/workloads'
      fullPath: '/infra/kubernetes/workloads/'
      preLoaderRoute: typeof InfraKubernetesWorkloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/kubernetes/workloads/$kind/$workloadName': {
      id: '/infra/kubernetes/workloads/$kind/$workloadName'
      path: '/infra/kubernetes/workloads/$kind/$workloadName'
      fullPath: '/infra/kubernetes/workloads/$kind/$workloadName'
      preLoaderRoute: typeof InfraKubernetesWorkloadsKindWorkloadNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LabRouteRouteChildren {
  LabAgentSessionRoute: typeof LabAgentSessionRoute
  LabAgentSessionsRoute: typeof LabAgentSessionsRoute
  LabChartsRoute: typeof LabChartsRoute
  LabErrorsRoute: typeof LabErrorsRoute
  LabFlowRoute: typeof LabFlowRoute
  LabNodesRoute: typeof LabNodesRoute
  LabOnboardingRoute: typeof LabOnboardingRoute
  LabQueryBuilderRoute: typeof LabQueryBuilderRoute
  LabServiceMap3dRoute: typeof LabServiceMap3dRoute
  LabTimelineRoute: typeof LabTimelineRoute
  LabWidgetsRoute: typeof LabWidgetsRoute
  LabIndexRoute: typeof LabIndexRoute
  LabBenchAgentTranscriptRoute: typeof LabBenchAgentTranscriptRoute
  LabBenchInfraRoute: typeof LabBenchInfraRoute
  LabBenchLogsRoute: typeof LabBenchLogsRoute
  LabBenchOverviewRoute: typeof LabBenchOverviewRoute
  LabBenchServiceDetailRoute: typeof LabBenchServiceDetailRoute
  LabBenchServiceMapRoute: typeof LabBenchServiceMapRoute
  LabBenchTanstackRoute: typeof LabBenchTanstackRoute
}

const LabRouteRouteChildren: LabRouteRouteChildren = {
  LabAgentSessionRoute: LabAgentSessionRoute,
  LabAgentSessionsRoute: LabAgentSessionsRoute,
  LabChartsRoute: LabChartsRoute,
  LabErrorsRoute: LabErrorsRoute,
  LabFlowRoute: LabFlowRoute,
  LabNodesRoute: LabNodesRoute,
  LabOnboardingRoute: LabOnboardingRoute,
  LabQueryBuilderRoute: LabQueryBuilderRoute,
  LabServiceMap3dRoute: LabServiceMap3dRoute,
  LabTimelineRoute: LabTimelineRoute,
  LabWidgetsRoute: LabWidgetsRoute,
  LabIndexRoute: LabIndexRoute,
  LabBenchAgentTranscriptRoute: LabBenchAgentTranscriptRoute,
  LabBenchInfraRoute: LabBenchInfraRoute,
  LabBenchLogsRoute: LabBenchLogsRoute,
  LabBenchOverviewRoute: LabBenchOverviewRoute,
  LabBenchServiceDetailRoute: LabBenchServiceDetailRoute,
  LabBenchServiceMapRoute: LabBenchServiceMapRoute,
  LabBenchTanstackRoute: LabBenchTanstackRoute,
}

const LabRouteRouteWithChildren = LabRouteRoute._addFileChildren(
  LabRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRouteRoute: LabRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  ChatRoute: ChatRoute,
  CliLoginRoute: CliLoginRoute,
  ConnectorsRoute: ConnectorsRoute,
  DeveloperRoute: DeveloperRoute,
  IntegrationsRoute: IntegrationsRoute,
  McpRoute: McpRoute,
  McpAuthorizeRoute: McpAuthorizeRoute,
  OrgRequiredRoute: OrgRequiredRoute,
  QuickStartRoute: QuickStartRoute,
  SelectPlanRoute: SelectPlanRoute,
  ServiceMapRoute: ServiceMapRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AgentSessionsSessionIdRoute: AgentSessionsSessionIdRoute,
  AlertsRuleIdRoute: AlertsRuleIdRoute,
  AlertsCreateRoute: AlertsCreateRoute,
  AnomaliesIncidentIdRoute: AnomaliesIncidentIdRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRoute,
  DashboardsTemplatesRoute: DashboardsTemplatesRoute,
  InfraHostNameRoute: InfraHostNameRoute,
  InfraDiscoverRoute: InfraDiscoverRoute,
  InvestigationsIdRoute: InvestigationsIdRoute,
  LogsLogIdRoute: LogsLogIdRoute,
  MetricsMetricNameRoute: MetricsMetricNameRoute,
  RecommendationsRecommendationKeyRoute: RecommendationsRecommendationKeyRoute,
  ReleasesCommitShaRoute: ReleasesCommitShaRoute,
  ReplaysSessionIdRoute: ReplaysSessionIdRoute,
  ServicesServiceNameRoute: ServicesServiceNameRoute,
  ShareTokenRoute: ShareTokenRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  AgentSessionsIndexRoute: AgentSessionsIndexRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  AnomaliesIndexRoute: AnomaliesIndexRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  ErrorsIndexRoute: ErrorsIndexRoute,
  InfraIndexRoute: InfraIndexRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MetricsIndexRoute: MetricsIndexRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
  ReplaysIndexRoute: ReplaysIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
  AlertsIncidentsIncidentIdRoute: AlertsIncidentsIncidentIdRoute,
  ErrorsIssuesIssueIdRoute: ErrorsIssuesIssueIdRoute,
  InfraCloudflareZoneNameRoute: InfraCloudflareZoneNameRoute,
  InfraContainersContainerNameRoute: InfraContainersContainerNameRoute,
  InfraPlanetscaleDbNameRoute: InfraPlanetscaleDbNameRoute,
  ErrorsIssuesIndexRoute: ErrorsIssuesIndexRoute,
  InfraCloudflareIndexRoute: InfraCloudflareIndexRoute,
  InfraContainersIndexRoute: InfraContainersIndexRoute,
  InfraKubernetesIndexRoute: InfraKubernetesIndexRoute,
  InfraPlanetscaleIndexRoute: InfraPlanetscaleIndexRoute,
  DashboardsDashboardIdWidgetsWidgetIdRoute:
    DashboardsDashboardIdWidgetsWidgetIdRoute,
  InfraKubernetesNodesNodeNameRoute: InfraKubernetesNodesNodeNameRoute,
  InfraKubernetesPodsPodNameRoute: InfraKubernetesPodsPodNameRoute,
  InfraKubernetesServicesServiceNameRoute:
    InfraKubernetesServicesServiceNameRoute,
  InfraKubernetesNodesIndexRoute: InfraKubernetesNodesIndexRoute,
  InfraKubernetesPodsIndexRoute: InfraKubernetesPodsIndexRoute,
  InfraKubernetesServicesIndexRoute: InfraKubernetesServicesIndexRoute,
  InfraKubernetesWorkloadsIndexRoute: InfraKubernetesWorkloadsIndexRoute,
  InfraKubernetesWorkloadsKindWorkloadNameRoute:
    InfraKubernetesWorkloadsKindWorkloadNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
