// Regenerates `src/generated/openrouter-catalog.ts` from OpenRouter's public
// model list. Run with `bun run --cwd lib/ai-model-catalog catalog:generate`
// whenever a model the dashboard shows resolves as unknown.
//
// No `--check` mode on purpose: the list changes weekly, so a freshness check
// in CI would fail on OpenRouter's schedule rather than ours.

import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { format } from "oxfmt"

const SOURCE = "https://openrouter.ai/api/v1/models"
const outputPath = fileURLToPath(new URL("../src/generated/openrouter-catalog.ts", import.meta.url))

interface OpenRouterModel {
	readonly id: string
	readonly canonical_slug: string
	readonly name: string
}

const response = await fetch(SOURCE)
if (!response.ok) throw new Error(`${SOURCE} answered ${response.status}`)
const { data } = (await response.json()) as { data?: ReadonlyArray<Partial<OpenRouterModel>> }
if (!Array.isArray(data) || data.length === 0) throw new Error(`${SOURCE} answered without a model list`)
for (const model of data) {
	if (
		typeof model.id !== "string" ||
		typeof model.canonical_slug !== "string" ||
		typeof model.name !== "string"
	) {
		throw new Error(`${SOURCE} lists a model without id/canonical_slug/name: ${JSON.stringify(model)}`)
	}
}

const models = [...(data as ReadonlyArray<OpenRouterModel>)].sort((a, b) => a.id.localeCompare(b.id))

// The vendor's display name is the prefix OpenRouter puts before ": " in the
// model name. Ids under `~` are OpenRouter's rolling aliases of a real vendor.
const vendors = new Map<string, string>()
for (const model of models) {
	const slug = model.id.split("/")[0]!.replace(/^~/, "")
	const separator = model.name.indexOf(": ")
	if (separator === -1 || vendors.has(slug)) continue
	vendors.set(slug, model.name.slice(0, separator))
}

const quote = (value: string) => JSON.stringify(value)

const lines = [
	"// GENERATED by scripts/generate-openrouter-catalog.ts — do not edit.",
	`// Source: ${SOURCE}`,
	`// Fetched: ${new Date().toISOString().slice(0, 10)}`,
	"",
	"/** `[id, canonicalSlug, name]` per model, as OpenRouter lists them. */",
	"export const OPENROUTER_MODELS: ReadonlyArray<readonly [id: string, canonicalSlug: string, name: string]> = [",
	...models.map((m) => `\t[${quote(m.id)}, ${quote(m.canonical_slug)}, ${quote(m.name)}],`),
	"]",
	"",
	"/** Vendor slug (the id's author segment) → the name OpenRouter prefixes model names with. */",
	"export const OPENROUTER_VENDORS: Readonly<Record<string, string>> = {",
	...[...vendors.entries()]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([slug, name]) => `\t${quote(slug)}: ${quote(name)},`),
	"} satisfies Record<string, string>",
	"",
]

// The repo's `.oxfmtrc.jsonc` settings; `format()` does not read the file.
const formatted = await format(outputPath, lines.join("\n"), {
	printWidth: 110,
	semi: false,
	tabWidth: 4,
	useTabs: true,
})
if (formatted.errors.length > 0) throw new Error(`Failed to format catalog: ${formatted.errors[0]?.message}`)
writeFileSync(outputPath, formatted.code)
console.log(`Wrote ${models.length} models, ${vendors.size} vendors to ${outputPath}`)
