import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { deriveAnticipatedIdentifiers } from "../src/anticipated-errors-derive"

const outputPath = fileURLToPath(
	new URL("../src/generated/anticipated-error-identifiers.ts", import.meta.url),
)
const checkMode = process.argv.includes("--check")
const identifiers = [...deriveAnticipatedIdentifiers()].sort()
const renderedModule = `// This file is generated by packages/domain/scripts/gen-anticipated-errors.ts
// Do not edit manually.
//
// Anticipated 4xx error identifiers are reflected from the domain HTTP
// contracts outside production so worker startup imports only this literal.

export const ANTICIPATED_ERROR_IDENTIFIER_LIST: ReadonlyArray<string> = [
${identifiers.map((identifier) => `\t${JSON.stringify(identifier)},`).join("\n")}
]
`

let existingModule = ""
try {
	existingModule = readFileSync(outputPath, "utf8")
} catch {
	existingModule = ""
}

if (checkMode) {
	if (existingModule !== renderedModule) {
		console.error("Anticipated error identifiers are out of date. Run `bun run gen:anticipated-errors`.")
		process.exit(1)
	}
	console.log(`Anticipated error identifiers are up to date (${identifiers.length} identifiers).`)
} else {
	mkdirSync(dirname(outputPath), { recursive: true })
	writeFileSync(outputPath, renderedModule)
	console.log(`Wrote ${identifiers.length} anticipated error identifiers to ${outputPath}.`)
}
