{{- if and .Values.agent.enabled .Values.agent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maple-k8s-infra.agent.serviceAccountName" . }}
  labels:
    {{- include "maple-k8s-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
{{- end }}
{{- if and .Values.agent.enabled (eq (include "maple-k8s-infra.cluster.enabled" .) "true") .Values.clusterCollector.serviceAccount.create }}
---
{{- end }}
{{- if and (eq (include "maple-k8s-infra.cluster.enabled" .) "true") .Values.clusterCollector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maple-k8s-infra.cluster.serviceAccountName" . }}
  labels:
    {{- include "maple-k8s-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-collector
{{- end }}
