#!/usr/bin/env bun
/**
 * Renders `skills/maple-dashboard-widgets/SKILL.md` from the same module that
 * backs the `describe_dashboard_schema` MCP tool.
 *
 * The skill file used to be hand-maintained beside hand-maintained tool
 * descriptions and a hand-maintained `maple://instructions`, which is three
 * copies of one truth and is exactly how they came to disagree: the skill still
 * shipped a v2 `{ endpoint, params }` widget template long after the decoders
 * moved to v3, and its gauge example paired `unit: "percent"` with a 0–100 arc —
 * the very mistake the write path now warns about.
 *
 *   bun run --cwd apps/api mcp:docs            # write
 *   bun run --cwd apps/api mcp:docs --check    # verify (CI)
 */
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { DASHBOARD_SCHEMA_SECTIONS, renderDashboardSchemaSection } from "@/mcp/lib/dashboard-schema-doc"

const SKILL_PATH = resolve(import.meta.dirname, "../../../skills/maple-dashboard-widgets/SKILL.md")

const FRONTMATTER = `---
name: maple-dashboard-widgets
description: "Build, repair, or review Maple dashboard widgets via the MCP. Triggers on phrases like 'create_dashboard', 'add_dashboard_widget', 'update_dashboard_widget', 'dashboard widget JSON', 'panel_type', 'QueryDraft', or any session that submits widget JSON to the maple MCP. Covers the panel-type table, the kind-discriminated data source, the percent vs percent_100 unit rule, valid aggregations and group-by tokens per source, the custom whereClause grammar, the scalar reduceToValue transform, and the verification step (MCP success != chart correctness)."
---
`

const INTRO = `
# Maple dashboard widgets via MCP

Everything below is generated from the live widget schema by
\`bun run --cwd apps/api mcp:docs\`. **Do not edit this file by hand** — edit
\`apps/api/src/mcp/lib/dashboard-schema-doc.ts\` and regenerate. The same module backs the
\`describe_dashboard_schema\` MCP tool, so an agent at runtime and a reader here see one truth.

## When to use this skill

When constructing widget JSON for \`mcp__maple__create_dashboard\`,
\`mcp__maple__add_dashboard_widget\`, \`mcp__maple__update_dashboard_widget\` or
\`mcp__maple__replace_dashboard_widgets\`.

For a brand-new dashboard, prefer the simplified \`widgets\` array on \`create_dashboard\`
(\`{ title, source, metric, group_by?, service_name?, unit? }\`) — it fills in the traps below.
Reach for raw JSON when the simplified spec can't express what you need: multi-query charts,
formulas, hidden series, non-default transforms.

## The three silent failures

1. **A data source is a \`kind\`-discriminated union.** \`{ "endpoint": …, "params": … }\` is the
   retired v2 shape and will not decode.
2. **\`percent\` means a 0–1 fraction; \`percent_100\` means 0–100.** Inverted from Grafana.
3. **\`groupBy\` is ignored unless \`addOns.groupBy\` is \`true\`.** No error, just an ungrouped total.

## Verification

MCP success is not chart correctness. The mutation tools reject queries the engine can't honor and
widgets that cannot render, and return an automatic \`inspect_chart_data\` summary for everything
else. Read the verdict: \`suspicious\` or \`broken\` means fix and resubmit.
`

const body = [
	FRONTMATTER.trimEnd(),
	INTRO.trimEnd(),
	...DASHBOARD_SCHEMA_SECTIONS.map((section) => renderDashboardSchemaSection(section)),
].join("\n\n")

const content = `${body}\n`

if (process.argv.includes("--check")) {
	const current = readFileSync(SKILL_PATH, "utf8")
	if (current !== content) {
		console.error(
			"skills/maple-dashboard-widgets/SKILL.md is out of date.\nRun: bun run --cwd apps/api mcp:docs",
		)
		process.exit(1)
	}
	console.log("SKILL.md is up to date.")
} else {
	writeFileSync(SKILL_PATH, content)
	console.log(`Wrote ${SKILL_PATH}`)
}
