#!/bin/sh
# Xcode Cloud runs this immediately after cloning, before it resolves the
# project. It has to exist because three things Xcode Cloud needs are
# deliberately gitignored:
#
#   Maple.xcodeproj              generated by XcodeGen (.pbxproj is merge-hostile)
#   Maple/Resources/Info.plist   generated from project.yml's `info:` block
#   Config/Secrets.xcconfig      real keys
#
# Every step announces itself, because the only way to debug this environment
# is the build log — there is no local emulator for it, and a bare "exited with
# code 1" says nothing about which step died.
set -eu

say() { echo "▸ ci_post_clone: $1"; }

say "starting"
say "repository path: ${CI_PRIMARY_REPOSITORY_PATH:-<unset>}"
cd "$CI_PRIMARY_REPOSITORY_PATH/apps/ios"
say "working directory: $(pwd)"

# --- XcodeGen ---------------------------------------------------------------
# Homebrew was a single point of failure here: one `brew install` and the whole
# build dies if the formula, the tap, or the runner's Homebrew is having a bad
# day. Try the cheap paths first and keep a version-pinned binary as a floor.
XCODEGEN_VERSION=2.46.0

if command -v xcodegen >/dev/null 2>&1; then
	say "xcodegen already on PATH ($(xcodegen --version 2>&1 | tr -d '\n'))"
elif brew install xcodegen; then
	say "xcodegen installed via Homebrew"
else
	say "Homebrew failed; falling back to the pinned release binary"
	TOOLS_DIR="$PWD/.ci-tools"
	mkdir -p "$TOOLS_DIR"
	curl -fsSL -o "$TOOLS_DIR/xcodegen.zip" \
		"https://github.com/yonaskolb/XcodeGen/releases/download/$XCODEGEN_VERSION/xcodegen.zip"
	unzip -oq "$TOOLS_DIR/xcodegen.zip" -d "$TOOLS_DIR"
	# The archive nests everything under `xcodegen/`, and the binary reads its
	# templates from the sibling `share/` — so the whole extracted tree has to
	# stay together and `bin` is one level deeper than the zip name suggests.
	PATH="$TOOLS_DIR/xcodegen/bin:$PATH"
	export PATH
	say "xcodegen $XCODEGEN_VERSION installed from the release archive"
fi

# --- Secrets ----------------------------------------------------------------
# The publishable key is a build input, not a secret in the confidentiality
# sense — the web app ships the same class of value in its JS bundle — but it
# still picks prod vs test, so it comes from the workflow environment rather
# than source. Set CLERK_PUBLISHABLE_KEY in App Store Connect → Xcode Cloud,
# either on the workflow or as a shared variable. Use the `pk_live_…` key: a
# `pk_test_` session is rejected by api.maple.dev, which is what a TestFlight
# build talks to.
if [ -z "${CLERK_PUBLISHABLE_KEY:-}" ]; then
	say "FATAL: CLERK_PUBLISHABLE_KEY is not set."
	say "Add it under Xcode Cloud → Workflow → Environment (or Shared"
	say "Environment Variables), then re-run this build."
	say "Environment variable names visible to this script:"
	env | cut -d= -f1 | sort | sed 's/^/    /'
	exit 1
fi
say "CLERK_PUBLISHABLE_KEY is set (${#CLERK_PUBLISHABLE_KEY} characters)"

# MAPLE_INGEST_KEY is deliberately NOT fatal when missing, unlike the Clerk key.
# Clerk absent means the app cannot sign in at all; telemetry absent means the
# SDK logs once and records nothing. Failing the build over it would block a
# release on an observability setting.
if [ -n "${MAPLE_INGEST_KEY:-}" ]; then
	say "MAPLE_INGEST_KEY is set (${#MAPLE_INGEST_KEY} characters)"
else
	say "MAPLE_INGEST_KEY is not set — this build ships without session replay or tracing."
	say "Add it under Xcode Cloud → Workflow → Environment to enable them."
fi

# DEVELOPMENT_TEAM is deliberately absent: Xcode Cloud manages signing itself,
# and an explicit team here fights its cloud-managed certificates.
cat >Config/Secrets.xcconfig <<EOF
CLERK_PUBLISHABLE_KEY = $CLERK_PUBLISHABLE_KEY
MAPLE_INGEST_KEY = ${MAPLE_INGEST_KEY:-}
EOF
say "wrote Config/Secrets.xcconfig"

# --- SPM build-tool plugins -------------------------------------------------
# MapleAPI's client is generated by swift-openapi-generator, a build-tool
# plugin. Xcode refuses to run an untrusted plugin and there is nobody to click
# the trust dialog on a build runner — locally this needs
# `-skipPackagePluginValidation`, and Xcode Cloud drives its own xcodebuild, so
# the equivalent has to be set as a default before it starts. The misspelled
# key is Apple's, not a typo here.
defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
say "allowed unattended SPM plugin and macro execution"

# --- Project ----------------------------------------------------------------
say "generating Maple.xcodeproj"
xcodegen generate
say "done"
